### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by entendu** [entendu/untrivializer#3]
Wat do

**Comment by copperwall** [comment]
This should be easy

**Comment by copperwall** [comment]
yeah

**Comment by entendu** [comment]
This should be easy and should be trivial

**Comment by entendu** [comment]
This should be easy and should be trivial

**Comment by entendu** [comment]
I set this up somewhere else. It should be easy.

**Comment by entendu** [comment]
This should be easy and should be trivial
